# Generated by Django 3.0 on 2020-07-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
