# Generated by Django 3.0 on 2020-07-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0004_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='color_code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
